name: admin-ui-parking-lot
namespace: official
version: 0.0.1
author: Wazo Team
display_name: Parking Lot
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-parking-lot
