name: admin-ui-parking-lot
namespace: official
version: 1.1.0-1
author: Wazo Team
display_name: Parking Lot
min_wazo_version: 18.01
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-parking-lot
